// todo: move to a secure place
const jwtSecret = 'My!@!Se3cr8tH4sh';
const tokenExpirationInSeconds = 36000;
const jwt = require('jsonwebtoken');
let crypto = require('crypto');
export class JwtService{
    public static generateToken(permissionLevel: Number) {
        try {

            let refreshId = '123321' + jwtSecret;
            let salt = crypto.randomBytes(16).toString('base64');
            let hash = crypto.createHmac('sha512', salt).update(refreshId).digest("base64");

            let expiresAt = new Date();
            expiresAt.setHours(expiresAt.getHours() + (tokenExpirationInSeconds / 3600));
            let token = jwt.sign({
                userId: '007',
                email: 'autogenerated@jwt.com',
                permissionLevel: permissionLevel,
                provider: 'email',
                name: 'bond',
                refreshKey: salt
            }, jwtSecret);
            let b = Buffer.from(hash);
            let refreshToken = b.toString('base64');
            return token;
        } catch (err) {
            throw err;
        }
    }
}